<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Carbon;
use Illuminate\Database\Eloquent\Builder;

/**
 * Class Book
 * @package App\Models\Book
 *
 * @property int    $id
 * @property int    $sub_category_id
 * @property int    $image_id
 * @property int    $file_id
 * @property float $rating
 * @property int    $publish_date
 *
 * @property Carbon $created_at
 * @property Carbon $updated_at
 */
class Book extends Model{
    /**
     * @var string
     */
    protected $table = 'books';

    /**
     * @var array
     */
    protected $fillablel = [
        'sub_category_id',
        'image_id',
        'like',
        'dislike',
        'publish_date'
    ];

    /**
     * @return Builder
     */
    public static function query(): Builder{
        return parent::query(); // TODO: Change the autogenerated stub
    }

    // Actions
    //

    // Getters
    /**
     * @return int
     */
    public function getId(): int{
        return $this->id;
    }

    /**
     * @return int
     */
    public function getSubCategoryId(): int{
        return $this->sub_category_id;
    }

    /**
     * @return int
     */
    public function getImageId():int{
        return $this->image_id;
    }

    /**
     * @return int
     */
    public function getFileId():int{
        return $this->file_id;
    }

    /**
     * @return float
     */
    public function getRating(): float{
        return $this->rating;
    }

    /**
     * @return int
     */
    public function getPublishDate(): int{
        return $this->publish_date;
    }

    /**
     * @return Carbon
     */
    public function getCreatedAt(): Carbon{
        return $this->created_at;
    }
}
